default_twitter: &default_twitter
  twitter_api_key: '3IkO6sip1S5A865VcYDapuQZc'
  twitter_api_secret: 'cTuXZdKzkmuqQZh4Ul5JV7JDbBNMYVkQ28hTLTpZBWLiMKNLcD'

development:
  secret_key_base: d45e2cffae3da5ae0f9b9d395fc09c4842a0b3b2ff8777c245d5fb3daa010780f6c5b3a7c2ac7d39a2e45aac4089d2ae4c5726c6e136d650ab5d55ed0cd7954f
  <<: *default_twitter

test:
  secret_key_base: 084729f5443400f802512ab51c31a21feedb91ab8c0cbdf34ded3ffaeaa0477a1f7cf0b16f41df84e51b4677739f68ade7b8324a7025b57950f97a5f513ab502
  <<: *default_twitter

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
