default_twitter: &default_twitter
  twitter_api_key: '<Your Key>'
  twitter_api_secret: '<Your Key>'

development:
  secret_key_base: <Your Key>
  <<: *default_twitter

test:
  secret_key_base: <Your Key>
  <<: *default_twitter

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
