# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca95e37bd1ceabc6294e3ccb8754aa729b363bb507b64aca45c4c70b7a0ab4ffbf7b74c3f2dec3fc9d9fd33c2a7799f4568ccef15a21798f476fc2669505a3a7

test:
  secret_key_base: 5aa5521d334ae45e12fd3dddf6c0fab0a93eae8d33595e67e8ead8940268caa118e5c73db5b69cd282cc8f56be98564eb256326a753cf99bd9899082301adea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
